### PR TITLE
Linux Experience Enhancement 

### PR DESCRIPTION
**Pull request by GroobleDierne**
### What it does
- Fix application not rendering on Wayland
- Fix calibration not working properly on Linux (commands were cut, incomplete, or not even pasted)

### How it's done
- Hardware acceleration was causing the "black screen", so I added a check to detect Wayland and turn off hardware acceleration accordingly as Java doesn't support it yet.
- I added delay between outputs in more places than what was previously done in KeyPreser and Calibrator.

Feel free to request any modification or clarification :frog:

### CODE REVIEW

**Comment by GroobleDierne** [comment]
Also 935da49df699ab389175b7b5c3e74efaf4d86caa doesn't seem to be needed anymore

**Comment by Ninjabrain1** [comment]
When you say 935da49df699ab389175b7b5c3e74efaf4d86caa is not needed any more, do you mean for all linux users? I dont know much about linux, is Wayland used by all linux users or is it something optional?

**Comment by GroobleDierne** [comment]
Wayland is a display server protocol it defines how the applications and the display server communicate to decide what to render on screen, Wayland is gradually replacing the former major display server protocol X11.
So every linux runner isn't using it but more and more will as major distributions are dropping support for X11 and the linux wall macro is currently being ported to Wayland.
As for the bug where ninbot crashed during startup I wasn't able to reproduce it when making this PR both when running Wayland and X11 (what I was running when the crash first happened and I created the issue) the splash screen was just skipped. Maybe it's a weird behavior caused by the fact that I was running the app in debug mode, I will try to package it and test this way to be sure.

**Comment by GroobleDierne** [comment]
What are you using to build the JAR? `mvn package` produces a jar with an incomplete manifest.

**Comment by Ninjabrain1** [comment]
I use `mvn clean compile assembly:single`

**Comment by GroobleDierne** [comment]
Okay so it was still causing issues but only when thee application was packaged, it should be good now and you won't need to ship two different versions of the app.

**Comment by GroobleDierne** [comment]
I found another problem, key codes aren't correctly parsed which makes it impossible to unbind a hotkey in top of displaying the wrong keys in the GUI. I'll try to fix that.

**Comment by GroobleDierne** [comment]
So I just tested this PR on both Linux and Windows and it works well, the only downside is that you will need to set your hotkeys again when using this version since now the keycode is stocked instead of the raw keycode.
The PR is ready to merge for me.

**Comment by Ninjabrain1** [comment]
Okay nice. Before merging ill investigate if there is a way to convert the old key codes in settings, so users dont have to re-enter all of them.

Thanks for fixing this!

**Pull request merged**
