### PR TITLE
add Optional language to display

### PR DESCRIPTION
**Pull request by LingMuQingYu**
add Optional language to display

### CODE REVIEW

**Comment by RedLime** [comment]
it is awesome, but I have one suggestion
I think all languages displays except English to be like `Language (English name)` to much better
example for Korean in Chinese, it becomes `韩语 (Korean)`

it is give consistency to the notation and could be revert the language if you accidentally change the language

**Comment by LingMuQingYu** [comment]
@RedLime The display of multiple languages together causes garbled characters！
image

**Comment by LingMuQingYu** [comment]
image
image

**Comment by RedLime** [comment]
yeah it is exactly what I said. that's so sick

**Comment by Ninjabrain1** [comment]
This is amazing, thank you!

**Pull request merged**
