### PR TITLE
Update I18n_zh_CN.properties

### PR DESCRIPTION
**Pull request by Crsuh2er0**

### CODE REVIEW

**Comment by Ninjabrain1** [comment]
Hi, thank you for translating. I just want to make sure this is correct (i might have caused some confusion earlier)


In english:

**Comment by Crsuh2er0** [comment]
Oh I found that I made some mistakes and I corrected them in #11 .

**Comment by liuzhengjin** [comment]
Thanks to @Crsuh2er0 for supporting this project.
感谢 泠羽_

**Comment by Crsuh2er0** [comment]
> Thanks to @Crsuh2er0 for supporting this project. 感谢 泠羽_

U r welcome.
在？用户名少打了个g？

**Comment by LinMuQingYu** [comment]
🤣

**Comment by LingMuQingYu** [comment]
@Crsuh2er0 大佬玩速通吗？我去给你点赞关注入团三连😄

**Comment by Crsuh2er0** [comment]
> @Crsuh2er0 大佬玩速通吗？我去给你点赞关注入团三连😄

Bilibili@泠羽_ 
平时玩的比较少qwq
<3

**Pull request merged**
